title: Miasteam - Ecommerce Operation Agency
email: lyanthinh03@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Agency Tăng trưởng E-commerce & Performance Marketing.

url: "https://miasteam.click" 
baseurl: ""

permalink: /:title/

# Build settings
markdown: kramdown
theme: minimal-mistakes-jekyll  # <-- PHẢI SỬA DÒNG NÀY

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache  # <-- PHẢI THÊM DÒNG NÀY
  - jekyll-sitemap        # <-- PHẢI THÊM DÒNG NÀY

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
  - README.md
  - .github/
  - admin/
include:
  - admin
