title: Miasteam - Ecommerce Operation Agency
email: lyanthinh03@gmail.com
description: >-
  Agency Tăng trưởng E-commerce & Performance Marketing.

url: "https://miasteam.click"
baseurl: ""

permalink: /:title/

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes   # <-- Dòng mới: BẮT BUỘC PHẢI CÓ

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-remote-theme                    # <-- Đảm bảo dòng này đã có

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
  - README.md
  - .github/
  - admin/
  - api/

include:
  - _pages
