title: Miasteam - Ecommerce Operation Agency
email: lyanthinh03@gmail.com
description: >-
  Agency Tăng trưởng E-commerce & Performance Marketing.

url: "https://miasteam.click"
baseurl: ""

permalink: /:title/

# Build settings
markdown: kramdown
theme: minimal-mistakes-jekyll

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache
  - jekyll-sitemap
  - minimal-mistakes-jekyll

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
  - README.md
  - .github/
  - admin/
  - api/ # [BẮT BUỘC PHẢI CÓ DÒNG NÀY]
include:
  - _pages
