title: Miasteam - Ecommerce Operation Agency
email: lyanthinh03@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Agency Tăng trưởng E-commerce & Performance Marketing.

url: "https://miasteam.click" # SỬA DÒNG NÀY
baseurl: ""

permalink: /:title/

# Build settings
markdown: kramdown
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
  - README.md
  - .github/
  - admin/
include:
  - admin
